import streamlit as st
#from dotenv import load_dotenv
import os
import openai
from diffusers import StableDiffusionPipeline
import torch

#load_dotenv()
openai.api_key = "xxxxx"

#function to generate AI based images using OpenAI Dall-E
def generate_images_using_openai(text):
    response = openai.Image.create(prompt=text,n=1,size="512x512")
    image_url = response['data'][0]['url']
    return image_url

#funtion to generate AI based images using HuggingFace diffusion
def generate_images_using_hugging_face_diffusion(text):
    pipe = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", torch_dtype=torch.float16)
    pipe = pipe.to("cuda")
    prompt = text
    image = pipe(prompt).images[0]
    return image

#Streamlit Code
choice = st.sidebar.selectbox("Select your choice", ["Home","DALL-E","Hugging Face"])

if choice == "Home":
    st.title("Imagination Image Generation")
    with st.expander("About the App"):
        st.write("This is a image generation app that uses AI to generates images from text prompt.")

elif choice == "DALL-E":
    st.subheader("Imagination Image Generation Using Open AI's DALL-E")
    input_prompt = st.text_input("Enter your prompt")
    if input_prompt is not None:
        if st.button("Generation Image"):
            image_url = generate_images_using_openai(input_prompt)
            st.image(image_url, caption="Generated by DALL-E")

elif choice == "Hugging Face":
    st.subheader("Imagination Image Generation Using Open AI's HuggingFace")
    input_prompt = st.text_input("Enter your prompt")
    if input_prompt is not None:
        if st.button("Generation Image"):
            image_output = generate_images_using_hugging_face_diffusion(input_prompt)
            st.success("Image Generated Successfully")
            st.image(image_output, caption="Generated by HuggingFace")



